POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "Adam",
    "lastName": "Woods"
}

###

POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "Carla",
    "lastName": "Jackson"
}

###

POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "James",
    "lastName": "Watson"
}

###

POST http://localhost:5000/employees
Content-Type: application/json

{
    "firstName": "Gregory",
    "lastName": "Colt"
}

###

# Neo4J queries
# (shift+ctrl+end, copy, paste)
CREATE (d1:Department {name: "Finance"});
CREATE (d2:Department {name: "Software Engineering"});
CREATE (d3:Department {name: "Design"});

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Woods" AND d.name = "Finance"
CREATE (n)-[:WORKS_IN]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Jackson" AND d.name = "Software Engineering"
CREATE (n)-[:WORKS_IN]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Watson" AND d.name = "Design"
CREATE (n)-[:WORKS_IN]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Colt" AND d.name = "Finance"
CREATE (n)-[:MANAGES]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Jackson" AND d.name = "Design"
CREATE (n)-[:MANAGES]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Woods" AND d.name = "Software Engineering"
CREATE (n)-[:MANAGES]->(d);

MATCH (n:Employee), (d:Department)
WHERE n.lastName = "Jackson" AND d.name = "Finance"
CREATE (n)-[:MANAGES]->(d);
